### ISSUE TITLE
skeleton admin login not working correctly 

### ISSUE THREAD

**Issue by techsolv** [getgrav/grav-theme-landio#1]
After I login, I get constantly redirected to {sitename}/user-login

in /user/config/plugins/login.yaml the default
route: /user-login
prevents the admin panel from loading.  

Commenting it out, allows the admin login console to appear as expected.

(noob)

**Comment by hexplor** [comment]
You are right. Fixing.

**Comment by hexplor** [comment]
Nope :) Actually make sure that you have:
- latest grav
- latest version of admin, login, form & email plugins 

After updating all should work :)
