### ISSUE TITLE
include a article list/blog template

### ISSUE THREAD

**Issue by techsolv** [getgrav/grav-theme-landio#2]
New Feature Request:

I was hooked on grav the instant I saw this theme.  But as a noob, I'm struggling a bit since this seems to be a "single page" template and not one that is flexible enough, e.g. I don't see how to display articles cleanly.  

In addition to a modular homepage, it would be valuable to add a menu that would produce a list of articles and/or be able to link to individual articles without the massive header image from the home page, e.g. simple details pages that are linked from the homepage or a blog listing.  

Would you be willing to expand the template to include another template that includes a article with a reduced header and an article listing that displays just the titles and slugs?

**Comment by hexplor** [comment]
Yeah, we are thinking about extending template a little bit. In the meantime you can use default layout (default.html.twig = default.md) and use 

``` yml
navbar_class: navbar-dark bg-inverse
```

in page header to avoid full image and change navbar behaviour. Menu system is already implement. If you add single page it will be reflected in the menu.
