### ISSUE TITLE
login template variable name

### ISSUE THREAD

**Issue by doodleslice** [getgrav/grav-theme-landio#5]
in /user/themes/landio/templates/partials/login-form.html.twig and in /user/themes/landio/templates/partials/navigation.html.twig the variable {{ 'LOGIN_PLUGIN.BTN_LOGIN'|t }} is used, but I believe it should be: {{ 'PLUGIN_LOGIN.BTN_LOGIN'|t }}

**Comment by flaviocopes** [comment]
Fixed already in the repo, needs a release of the theme: https://github.com/getgrav/grav-theme-landio/commit/933aeaeb9b791222116657f7a490bbbf053f98b9
